const jobs = [
  {id:1,title:'Werkstudent Marketing & Communications',company:'KOMET GmbH',location:'Mannheim',distance:17,type:'Werkstudent',format:'Hybrid',score:91,age:'2 ч. назад',logo:'K',color:'blue',description:'Поддержка команды маркетинга, digital campaigns и коммуникаций для B2B-аудитории.',reasons:['Сильное совпадение с маркетингом и контентом','Требуется уверенный English','Гибридный формат подтверждён'],gap:'Уточните требуемый уровень немецкого.'},
  {id:2,title:'Praktikum Business Development',company:'Getsafe',location:'Heidelberg',distance:3,type:'Praktikum',format:'Office',score:87,age:'5 ч. назад',logo:'G',color:'pink',description:'Исследование рынка, подготовка встреч с партнёрами и поддержка sales pipeline.',reasons:['Опыт customer acquisition и продаж','Соответствует направлению Business Development','Офис в Heidelberg'],gap:'Проверьте даты стажировки.'},
  {id:3,title:'Werkstudent Social Media & Content',company:'MARSCHPAT',location:'Walldorf',distance:14,type:'Werkstudent',format:'Hybrid',score:82,age:'вчера',logo:'M',color:'',description:'Создание short-form видео, контент-планов и аналитика социальных сетей.',reasons:['Релевантный опыт mobile videography','Достижение 70M+ просмотров','Гибридный формат'],gap:'Подготовьте примеры работ/портфолио.'},
  {id:4,title:'Praktikum Sales Operations',company:'Roche',location:'Mannheim',distance:18,type:'Praktikum',format:'Office',score:78,age:'вчера',logo:'R',color:'blue',description:'Поддержка коммерческой команды, CRM и подготовка аналитических материалов.',reasons:['Sales и customer acquisition в профиле','Офис в радиусе поиска'],gap:'Требования к Excel следует уточнить.'},
  {id:5,title:'Ehrenamt Kommunikation',company:'Caritas Rhein-Neckar',location:'Heidelberg',distance:4,type:'Ehrenamt',format:'Office',score:73,age:'2 дня назад',logo:'C',color:'pink',description:'Помощь с событиями, локальными коммуникациями и контентом для социальных сетей.',reasons:['Подходит опыт контента и коммуникаций','Волонтёрская роль в центре Heidelberg'],gap:'Уточните регулярность участия.'},
  {id:6,title:'Working Student Growth Marketing',company:'IntelliShop',location:'Karlsruhe',distance:54,type:'Werkstudent',format:'Hybrid',score:88,age:'3 дня назад',logo:'I',color:'',description:'Growth experiments and digital content.',reasons:['Marketing match'],gap:'За пределами радиуса; не рекомендуется.'}
];
let visibleJobs = jobs.filter(j=>j.distance<=40); let selectedJob=null;
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const defaultApplications=[{jobId:1,status:'Черновик готов'},{jobId:3,status:'Черновик готов'},{jobId:2,status:'Отправлено вручную',sentAt:'2026-09-11T09:36:00'}];
let applications=JSON.parse(localStorage.getItem('careerAgentApplications')||'null')||defaultApplications;
const applicationFor=id=>applications.find(item=>item.jobId===id);
const sentLabel=iso=>new Intl.DateTimeFormat('ru-RU',{dateStyle:'medium',timeStyle:'short'}).format(new Date(iso));
function saveApplications(){localStorage.setItem('careerAgentApplications',JSON.stringify(applications));}
function logo(job){return `<span class="company-logo ${job.color}">${job.logo}</span>`}
function jobCard(job, compact=false){const app=applicationFor(job.id),sent=app?.status==='Отправлено вручную',status=sent?`<span class="applied-badge">✓ ОТКЛИК ОТПРАВЛЕН</span>`:`<span class="tag ${job.format==='Hybrid'?'hybrid':''}">${job.format==='Hybrid'?'Гибрид':'Офис'}</span>`;return compact?`<article class="featured-card" data-job="${job.id}">${logo(job)}<div><h3>${job.title}</h3><p>${job.company} · ${job.location} · ${job.distance} км</p></div>${status}<div class="score"><b>${job.score}%</b><span>СОВПАДЕНИЕ</span></div></article>`:`<article class="job-card" data-job="${job.id}"><div class="job-top">${logo(job)}${status}</div><h3>${job.title}</h3><p>${job.company} · ${job.location}</p><p class="job-desc">${job.description}</p>${sent?`<p class="sent-at">Отправлено: ${sentLabel(app.sentAt)}</p>`:''}<div class="job-footer"><span class="distance">⌖ ${job.distance} км · ${job.age}</span><div class="score"><b>${job.score}%</b><span>СОВПАД.</span></div></div></article>`}
function renderJobs(){let term=$('#jobSearch').value.toLowerCase(),type=$('#typeFilter').value,format=$('#formatFilter').value,sort=$('#sortJobs').value;let list=visibleJobs.filter(j=>(j.title+j.company).toLowerCase().includes(term)&&(type==='all'||j.type===type)&&(format==='all'||j.format===format));list.sort((a,b)=>{const aSent=applicationFor(a.id)?.status==='Отправлено вручную',bSent=applicationFor(b.id)?.status==='Отправлено вручную';if(aSent!==bSent)return aSent?1:-1;return sort==='score'?b.score-a.score:sort==='distance'?a.distance-b.distance:a.id-b.id});$('#jobGrid').innerHTML=list.length?list.map(j=>jobCard(j)).join(''):'<p>По этому запросу вакансий пока нет.</p>';$$('[data-job]').forEach(x=>x.onclick=()=>openJob(+x.dataset.job));}
function openJob(id){selectedJob=jobs.find(j=>j.id===id);let j=selectedJob;$('#dialogContent').innerHTML=`<div class="job-dialog"><div class="dialog-score"><b>${j.score}%</b><small>совпадение</small></div><p class="eyebrow">${j.type.toUpperCase()} · ${j.format.toUpperCase()}</p><h2>${j.title}</h2><p class="dialog-subtitle">${j.company} · ${j.location} · ${j.distance} км от Heidelberg</p><div class="dialog-section"><h4>ПОЧЕМУ ПОДХОДИТ</h4><ul>${j.reasons.map(r=>`<li>${r}</li>`).join('')}</ul></div><div class="dialog-section"><h4>ОПИСАНИЕ</h4><p>${j.description}</p></div><div class="dialog-section"><h4>ПРОВЕРЬТЕ ПЕРЕД ОТКЛИКОМ</h4><p>${j.gap}</p></div><div class="dialog-actions"><button class="outline-button" data-close>Сохранить</button><button class="solid-button" id="prepareDraft">Подготовить отклик</button></div></div>`;$('#jobDialog').showModal();$('#prepareDraft').onclick=openDraft;$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());}
function openDraft(){ $('#jobDialog').close();let j=selectedJob;$('#draftTitle').textContent=`Отклик: ${j.company}`;$('#draftText').value=`Betreff: Bewerbung als ${j.title}\n\nSehr geehrtes ${j.company}-Team,\n\nmit großem Interesse habe ich Ihre Stelle als ${j.title} entdeckt. Als angehender Student der International Business Administration an der SRH University Heidelberg bringe ich praktische Erfahrung in Marketing, Kundenakquise und Content Creation mit.\n\nIn meiner bisherigen Arbeit habe ich Werbematerialien und Social-Media-Inhalte für Unternehmen erstellt und dabei Kund:innenkommunikation sowie erste Sales- und Business-Development-Aufgaben unterstützt. Besonders gern möchte ich diese Erfahrung in Ihrem Team einbringen und weiterentwickeln.\n\nMeine Verfügbarkeit kläre ich gern persönlich mit Ihnen. Ich freue mich auf die Möglichkeit, mich vorzustellen.\n\nMit freundlichen Grüßen\nAlizhan Nurzhan`;$('#resumeAttached').checked=false;$('#markApplied').disabled=true;$('#resumeAttached').onchange=e=>$('#markApplied').disabled=!e.target.checked;$('#draftDialog').showModal();}
function showToast(text){let t=$('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function renderKanban(){let columns=['Черновик готов','Отправлено вручную','Интервью','Архив'];$('#kanban').innerHTML=columns.map(title=>{const entries=applications.filter(item=>item.status===title).map(item=>({...item,job:jobs.find(job=>job.id===item.jobId)})).filter(item=>item.job);return `<section class="kanban-column"><div class="kanban-head"><span>${title}</span><span>${entries.length}</span></div>${entries.map(({job,sentAt})=>`<article class="tracker-card"><h4>${job.title}</h4><p>${job.company} · ${job.location}</p>${sentAt?`<p class="sent-at">Отправлено: ${sentLabel(sentAt)}</p>`:''}</article>`).join('')}</section>`}).join('')}
$$('.nav-item,[data-page]').forEach(b=>b.addEventListener('click',()=>{let p=b.dataset.page;if(!p)return;$$('.page').forEach(x=>x.classList.remove('active'));$(`#${p}`).classList.add('active');$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===p));$('#crumb').textContent=b.textContent.trim().replace(/\d+/g,'')||'Обзор';$('#crumb-detail').textContent=p==='dashboard'?'Сегодня':'';$('.sidebar').classList.remove('open');window.scrollTo(0,0)}));
$('#featuredList').innerHTML=jobs.slice(0,3).map(j=>jobCard(j,true)).join('');$$('.featured-card').forEach(x=>x.onclick=()=>openJob(+x.dataset.job));
['jobSearch','typeFilter','formatFilter','sortJobs'].forEach(id=>$('#'+id).addEventListener('input',renderJobs));renderJobs();renderKanban();
$$('[data-stat-action]').forEach(button=>button.onclick=()=>{const action=button.dataset.statAction;if(action==='drafts'){$$('[data-page="tracker"]')[0].click();return;}$$('[data-page="vacancies"]')[0].click();$('#jobSearch').value='';$('#typeFilter').value='all';$('#formatFilter').value='all';$('#sortJobs').value='score';visibleJobs=jobs.filter(job=>job.distance<=40);if(action==='matches'){visibleJobs=visibleJobs.filter(job=>job.score>=70);showToast('Показаны вакансии с соответствием от 70%')}else{showToast('Показаны новые вакансии в радиусе 40 км')}renderJobs();});
$('#syncButton').onclick=()=>{let btn=$('#syncButton');btn.innerHTML='<span>↻</span> Ищем…';setTimeout(()=>{btn.innerHTML='<span>✓</span> Обновлено';showToast('Проверено 36 источников · 4 новых вакансии');setTimeout(()=>btn.innerHTML='<span>↻</span> Обновить вакансии',1800)},1100)};
$('#filterToggle').onclick=()=>$('#filterBar').classList.toggle('open');$('#radius').oninput=e=>$('#radiusOut').textContent=e.target.value+' км';$('#saveProfile').onclick=e=>{e.preventDefault();showToast('Настройки профиля сохранены')};$('#copyDraft').onclick=()=>navigator.clipboard.writeText($('#draftText').value).then(()=>showToast('Черновик скопирован в буфер обмена'));$('#markApplied').onclick=()=>{const existing=applicationFor(selectedJob.id);if(existing){existing.status='Отправлено вручную';existing.sentAt=new Date().toISOString();}else applications.push({jobId:selectedJob.id,status:'Отправлено вручную',sentAt:new Date().toISOString()});saveApplications();$('#draftDialog').close();renderKanban();renderJobs();$('#featuredList').innerHTML=jobs.slice(0,3).map(j=>jobCard(j,true)).join('');$$('.featured-card').forEach(x=>x.onclick=()=>openJob(+x.dataset.job));showToast('Отклик отмечен как отправленный: '+sentLabel(applicationFor(selectedJob.id).sentAt));};$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('.mobile-menu').onclick=()=>$('.sidebar').classList.toggle('open');$('#addTracker').onclick=()=>showToast('Выберите вакансию в разделе «Вакансии»');
